/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import SanPham.*;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class PanelNSX extends javax.swing.JPanel {

    /**
     * Creates new form PanelNSX
     */
    public PanelNSX() {
        initComponents();
        initModel();
        txtMaNSX.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNSX = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        grNSX = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtMaNSX = new javax.swing.JTextField();
        txtTenNSX = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtWebsite = new javax.swing.JTextField();
        txtLogo = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        btnThemNSX = new javax.swing.JButton();
        btnCapNhatNSX = new javax.swing.JButton();
        grNSXSP = new javax.swing.JScrollPane();
        grLoaiSP = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        labelhinh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        pnNSX.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 255)));
        pnNSX.setMaximumSize(new java.awt.Dimension(670, 550));
        pnNSX.setMinimumSize(new java.awt.Dimension(670, 550));
        pnNSX.setPreferredSize(new java.awt.Dimension(727, 500));

        grNSX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NSX", "Tên NSX", "Email", "Website", "Logo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grNSXMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(grNSX);
        if (grNSX.getColumnModel().getColumnCount() > 0) {
            grNSX.getColumnModel().getColumn(0).setResizable(false);
            grNSX.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Tên NSX");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Email");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Website");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Logo");

        txtMaNSX.setEnabled(false);

        txtTenNSX.setEnabled(false);

        txtEmail.setEnabled(false);

        txtWebsite.setEnabled(false);

        txtLogo.setEnabled(false);

        btnFile.setText("Chọn file");
        btnFile.setEnabled(false);
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        btnThemNSX.setText("Thêm");
        btnThemNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNSXActionPerformed(evt);
            }
        });

        btnCapNhatNSX.setText("Cập nhật");
        btnCapNhatNSX.setEnabled(false);
        btnCapNhatNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNSXActionPerformed(evt);
            }
        });

        grLoaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grNSXSP.setViewportView(grLoaiSP);
        if (grLoaiSP.getColumnModel().getColumnCount() > 0) {
            grLoaiSP.getColumnModel().getColumn(0).setResizable(false);
            grLoaiSP.getColumnModel().getColumn(0).setPreferredWidth(10);
            grLoaiSP.getColumnModel().getColumn(1).setResizable(false);
        }

        btnXoa.setText("Xoá");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        labelhinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1ed84e97.png"))); // NOI18N

        jButton1.setText("Huỷ bỏ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNSXLayout = new javax.swing.GroupLayout(pnNSX);
        pnNSX.setLayout(pnNSXLayout);
        pnNSXLayout.setHorizontalGroup(
            pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNSXLayout.createSequentialGroup()
                .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnNSXLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnNSXLayout.createSequentialGroup()
                                .addComponent(btnThemNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCapNhatNSX)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnNSXLayout.createSequentialGroup()
                                .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnNSXLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel23))
                                        .addComponent(jLabel22)))
                                .addGap(24, 24, 24)
                                .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLogo)
                                    .addComponent(txtTenNSX)
                                    .addComponent(txtWebsite)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFile)
                                    .addComponent(labelhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtMaNSX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grNSXSP, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNSXLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnNSXLayout.setVerticalGroup(
            pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNSXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNSXLayout.createSequentialGroup()
                        .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNSXLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFile))
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCapNhatNSX)
                                .addComponent(btnThemNSX))
                            .addGroup(pnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnXoa)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnNSXLayout.createSequentialGroup()
                        .addComponent(grNSXSP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void grNSXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grNSXMouseClicked
        // TODO add your handling code here:
        setnullfield();
        filldataFromTable();
        btnCapNhatNSX.setEnabled(true);
        btnXoa.setEnabled(true);
        btnThemNSX.setEnabled(false);

        model1.setRowCount(0);
        Sanpham s = new Sanpham();

        for (Sanpham sp : s.getListSP_NSX(txtMaNSX.getText().toString())) {
            model1.addRow(sp.toVector());

        }
    }//GEN-LAST:event_grNSXMouseClicked

    private void btnThemNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNSXActionPerformed
        Pattern p = null;
        Matcher m = null;

        if (btnThemNSX.getText().equalsIgnoreCase("Thêm")) {
            btnFile.setEnabled(true);
            btnThemNSX.setText("Lưu");

            btnCapNhatNSX.setEnabled(false);
            btnXoa.setEnabled(false);
            txtMaNSX.setEnabled(false);
            txtTenNSX.setEnabled(true);
            txtEmail.setEnabled(true);
            txtWebsite.setEnabled(true);

            txtMaNSX.setText(null);
            txtTenNSX.setText(null);
            txtEmail.setText(null);
            txtWebsite.setText(null);
            txtLogo.setText(null);

        } else {
            NSX n1 = new NSX();

            n1.findten(txtTenNSX.getText().trim());

            if (n1.findten(txtTenNSX.getText().toString())) {
                JOptionPane.showMessageDialog(null, "Tên NSX đã tồn tại");
                return;
            }
            if (txtTenNSX.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Không được bỏ trống tên nhà sản xuất");
                return;
            }

            do {
                p = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
                m = p.matcher(txtEmail.getText());
                if (!m.matches()) {
                    JOptionPane.showMessageDialog(null, "Nhập sai định dạng Email");
                    return;
                }

                break;

            } while (true);

            if (txtWebsite.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Không được bỏ trống Website");
                return;
            }

            SanPham.NSX n = new SanPham.NSX(txtTenNSX.getText(), txtEmail.getText(), txtWebsite.getText(), txtLogo.getText());
            if (n.insert(n) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                model.setRowCount(0);
                initModel();
                setnullfield();
                txtEmail.setEnabled(false);
                txtTenNSX.setEnabled(false);
                txtMaNSX.setEnabled(false);
                txtWebsite.setEnabled(false);
                btnThemNSX.setText("Thêm");
                btnCapNhatNSX.setEnabled(false);
                btnXoa.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
            }

        }
    }//GEN-LAST:event_btnThemNSXActionPerformed

    private void btnCapNhatNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNSXActionPerformed
        
        Pattern p = null;
        Matcher m = null;
        int i = grNSX.getSelectedRow();

        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Chưa chọn dòng");
            return;
        }
        if (btnCapNhatNSX.getText().equalsIgnoreCase("Cập nhật")) {

            btnCapNhatNSX.setText("Lưu");
            btnThemNSX.setEnabled(false);
            btnXoa.setEnabled(false);
            txtTenNSX.setEnabled(true);
            txtEmail.setEnabled(true);
            txtWebsite.setEnabled(true);
            btnFile.setEnabled(true);

        } else {

            if (txtMaNSX.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Khong duoc bo trong MaNSX");
                return;
            }

            if (txtTenNSX.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Khong duoc bo trong TenNSX");
                return;
            }
            for (int j = 0; j < listCapNhat.size(); j++) {
                int mansx = Integer.parseInt(txtMaNSX.getText().toString());
                String tennsx = txtTenNSX.getText().toString();
                NSX na = listCapNhat.get(j);

                if (!(na.getMaNSX() == mansx) && na.getTenNSX().equalsIgnoreCase(tennsx)) {
                    JOptionPane.showMessageDialog(null, "Trùng tên nhà sản xuất");
                    return;
                }
            }

            if (txtEmail.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Khong duoc bo trong Email");
                return;
            }
             do {
                p = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
                m = p.matcher(txtEmail.getText());
                if (!m.matches()) {
                    JOptionPane.showMessageDialog(null, "Nhập sai định dạng Email");
                    return;
                }

                break;

            } while (true);
            if (txtWebsite.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Khong duoc bo trong Website");
                return;
            }

            SanPham.NSX n = new SanPham.NSX(Integer.parseInt(txtMaNSX.getText().toString()), txtTenNSX.getText(), txtEmail.getText(), txtWebsite.getText(), txtLogo.getText());

            if (n.update(n) > 0) {

                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                initModel();

                btnCapNhatNSX.setText("Cập nhật");
                btnThemNSX.setEnabled(true);
                txtEmail.setEnabled(false);
                btnFile.setEnabled(false);
                txtMaNSX.setEnabled(false);
                txtTenNSX.setEnabled(false);
                txtWebsite.setEnabled(false);
                labelhinh.setIcon(null);
                btnXoa.setEnabled(true);
                setnullfield();
            } else {
                JOptionPane.showMessageDialog(null, "Cap nhat that bai");
            }
        }
    }//GEN-LAST:event_btnCapNhatNSXActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = grNSX.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Chưa chọn nhà sản xuất");
            return;
        }
        SanPham.NSX n = new SanPham.NSX(Integer.parseInt(txtMaNSX.getText().toString()), txtTenNSX.getText(), txtEmail.getText(), txtWebsite.getText(), txtLogo.getText());

        for (int j = 0; j < listSanPham.size(); j++) {
            Sanpham get = listSanPham.get(j);
            String MaNSX = get.getMaNSX();

            if (txtMaNSX.getText().toString().equalsIgnoreCase(MaNSX)) {
                JOptionPane.showMessageDialog(null, "Đã nhập mặt hàng từ nhà sản xuất");
                return;
            }
        }

        int r = JOptionPane.showConfirmDialog(null, "Xác nhận xóa nhà sản xuất?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            if (n.delete(n) > 0) {
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                setnullfield();
                File f = new File(txtLogo.getText());
                try {
                    Files.delete(f.toPath());
                } catch (IOException ex) {
                    //JOptionPane.showMessageDialog(null, "Loi : ");
                }
                model.removeRow(i);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        // TODO add your handling code here:
        image();

    }//GEN-LAST:event_btnFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        initModel();
        setnullfield();
        btnThemNSX.setText("Thêm");
        btnCapNhatNSX.setText("Cập nhật");
        btnThemNSX.setEnabled(true);
        btnCapNhatNSX.setEnabled(false);
        btnXoa.setEnabled(false);
        txtEmail.setEnabled(false);
        txtMaNSX.setEnabled(false);
        txtTenNSX.setEnabled(false);
        txtWebsite.setEnabled(false);
        btnFile.setEnabled(false);
        ImageIcon logoresized = new ImageIcon("src/Image/1ed84e97.png");
        Image scaleImage = logoresized.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);

        labelhinh.setIcon(new ImageIcon(scaleImage));

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatNSX;
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnThemNSX;
    private javax.swing.JButton btnXoa;
    private javax.swing.JTable grLoaiSP;
    private javax.swing.JTable grNSX;
    private javax.swing.JScrollPane grNSXSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelhinh;
    private javax.swing.JPanel pnNSX;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogo;
    private javax.swing.JTextField txtMaNSX;
    private javax.swing.JTextField txtTenNSX;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel model, model1;
    ArrayList<NSX> listCapNhat;
    ArrayList<Sanpham> listSanPham;

    private void initModel() {

        model = (DefaultTableModel) grNSX.getModel();
        model1 = (DefaultTableModel) grLoaiSP.getModel();

        model.setRowCount(0);
        model1.setRowCount(0);

        listSanPham = new ArrayList<>();
        listSanPham.clear();

        Sanpham s = new Sanpham();
        listSanPham = s.getList();
        for (Sanpham sp : s.getList()) {
            model1.addRow(sp.toVector());

        }
        listCapNhat = new ArrayList<>();
        listCapNhat.clear();
        SanPham.NSX n = new SanPham.NSX();
        listCapNhat = n.getList();
        for (SanPham.NSX nsx : n.getList()) {

            model.addRow(nsx.toVector());

        }

    }

    private void filldataFromTable() {
        //lay chi so dong duoc chon tren Table
        int i = grNSX.getSelectedRow();

        if (i < 0) {
            return;
        }
        txtMaNSX.setText(grNSX.getValueAt(i, 0).toString());
        txtTenNSX.setText(grNSX.getValueAt(i, 1).toString());
        txtEmail.setText(grNSX.getValueAt(i, 2).toString());
        txtWebsite.setText(grNSX.getValueAt(i, 3).toString());
        ImageIcon logoresized = new ImageIcon(grNSX.getValueAt(i, 4).toString());
        Image scaleImage = logoresized.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
        labelhinh.setIcon(new ImageIcon(scaleImage));
        txtLogo.setText(grNSX.getValueAt(i, 4).toString());
    }

    private void image() {
        if (txtTenNSX.getText().isEmpty() && txtTenNSX.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên NSX trước khi chọn ảnh");
            return;
        }
        JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
        int i = fc.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fc.getSelectedFile();
                File filepath = new File(file.getAbsolutePath());
                File logo = new File("logo/" + txtTenNSX.getText() + ".jpg");
                Files.copy(filepath.toPath(), logo.toPath(), StandardCopyOption.REPLACE_EXISTING);
                ImageIcon logoresized = new ImageIcon(logo.getPath());
                Image scaleImage = logoresized.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
                labelhinh.setIcon(new ImageIcon(scaleImage));
                txtLogo.setText(logo.getPath());
            } catch (IOException ex) {
                System.out.println("Loi NSX: " + ex.getMessage());
            }
        }
    }

    private void setnullfield() {
        txtTenNSX.setText(null);
        txtMaNSX.setText(null);
        txtEmail.setText(null);
        txtWebsite.setText(null);
        txtLogo.setText(null);
    }
}
